//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalBuster
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Calorie_BusterEntities : DbContext
    {
        public Calorie_BusterEntities()
            : base("name=Calorie_BusterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FoodItem_tbl> FoodItem_tbl { get; set; }
        public DbSet<Link_tbl> Link_tbl { get; set; }
        public DbSet<Meal_tbl> Meal_tbl { get; set; }
        public DbSet<PastLink_tbl> PastLink_tbl { get; set; }
        public DbSet<PastMeal_tbl> PastMeal_tbl { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User_tbl> User_tbl { get; set; }
    }
}
