//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class dryGoods_tbl
    {
        public int item_id { get; set; }
        public string itemName { get; set; }
        public Nullable<int> gPerUnit { get; set; }
        public Nullable<decimal> pricePerItem { get; set; }
        public Nullable<double> protien { get; set; }
        public Nullable<double> carbs { get; set; }
        public Nullable<double> sugar { get; set; }
        public Nullable<double> fat { get; set; }
        public Nullable<double> sodium { get; set; }
        public Nullable<double> calorie { get; set; }
        public string typeOf { get; set; }
    }
}
