//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class link_tbl
    {
        public int link_id { get; set; }
        public Nullable<int> dinner_id { get; set; }
        public Nullable<int> dbl_id { get; set; }
        public Nullable<int> meat_id { get; set; }
        public Nullable<int> veg_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<decimal> amount { get; set; }
    }
}
