//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class meatFish_tbl
    {
        public int meat_id { get; set; }
        public string name { get; set; }
        public Nullable<short> gPerUnit { get; set; }
        public Nullable<decimal> pricePerGram { get; set; }
    }
}
