//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dinner_tbl> dinner_tbl { get; set; }
        public DbSet<double_tbl> double_tbl { get; set; }
        public DbSet<link_tbl> link_tbl { get; set; }
        public DbSet<meatFish_tbl> meatFish_tbl { get; set; }
        public DbSet<pastMeals_tbl> pastMeals_tbl { get; set; }
        public DbSet<veg_tbl> veg_tbl { get; set; }
        public DbSet<dryGoods_tbl> dryGoods_tbl { get; set; }
    }
}
