//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastMeal_tbl
    {
        public PastMeal_tbl()
        {
            this.PastLink_tbl = new HashSet<PastLink_tbl>();
        }
    
        public int PastMeal_id { get; set; }
        public int User_id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<PastLink_tbl> PastLink_tbl { get; set; }
        public virtual User_tbl User_tbl { get; set; }
    }
}
