//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalBuster
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_tbl
    {
        public User_tbl()
        {
            this.PastMeal_tbl = new HashSet<PastMeal_tbl>();
        }
    
        public int User_id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<PastMeal_tbl> PastMeal_tbl { get; set; }
    }
}
